version: "3.4"

services:
  proxy:
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/ssl:/etc/nginx/ssl
    restart: unless-stopped

  web:
    image: ghcr.io/kofeebrian/short-url-frontend:main
    ports:
      - 3000:3000
    # volumes:
    #   - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - API_ENDPOINT=http://localhost:3001/api

  server:
    image: ghcr.io/kofeebrian/short-url-backend:main
    # build:
    #   context: server/
    #   dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    env_file:
      - server/.env
    environment:
      - MONGO_URI=
      - SERVER_NAME=http://localhost:8080
      - SECRET_KEY=secret

  db:
    ports:
      - 27100:27017
    volumes:
      - ./data/dev/mongo:/data/db