version: "3.4"

services:
  proxy:
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/ssl:/etc/nginx/ssl
    restart: unless-stopped

  web:
    build: 
      context: .
      dockerfile: Dockerfile.development
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - .env.local

  server:
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    env_file:
      - server/.env.development.local

  db:
    ports:
      - 27100:27017
    volumes:
      - ./data/dev/mongo:/data/db